# Generated by Django 2.2.9 on 2020-02-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
