# Generated by Django 2.2.9 on 2020-02-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='author',
        ),
    ]
