# Generated by Django 2.2.9 on 2020-02-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200205_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
    ]
